import type { RuleMetadata } from './types.js';

const entries = [
  ['STRUCT-001', 'REFERENCE_NOT_FOUND', 'STRUCTURAL', 1, 'ERROR'],
  ['STRUCT-002', 'DUPLICATE_ENDPOINT', 'STRUCTURAL', 2, 'ERROR'],
  ['STRUCT-003', 'INVALID_ENDPOINT_COUNT', 'STRUCTURAL', 2, 'ERROR'],
  ['STRUCT-004', 'TOPOLOGY_MISMATCH', 'STRUCTURAL', 2, 'ERROR'],
  ['IFACE-001', 'INTERFACE_INCOMPATIBLE', 'INTERFACE', 3, 'ERROR'],
  ['IFACE-002', 'DIRECTION_CONFLICT', 'INTERFACE', 3, 'ERROR'],
  ['IFACE-003', 'INTERFACE_CONVERTER_REQUIRED', 'INTERFACE', 3, 'ERROR'],
  ['IFACE-004', 'CUSTOM_INTERFACE_UNVERIFIED', 'INTERFACE', 3, 'WARNING'],
  ['IFACE-005', 'PROTOCOL_MISMATCH', 'INTERFACE', 3, 'ERROR'],
  ['IFACE-006', 'PROTOCOL_VALIDATION_INCOMPLETE', 'INTERFACE', 3, 'WARNING'],
  ['ELEC-001', 'LOGIC_VOLTAGE_INCOMPATIBLE', 'ELECTRICAL', 4, 'ERROR'],
  ['ELEC-002', 'ELECTRICAL_LIMITS_INCOMPLETE', 'ELECTRICAL', 4, 'WARNING'],
  ['ELEC-003', 'ANALOG_RANGE_INCOMPATIBLE', 'ELECTRICAL', 4, 'ERROR'],
  ['ELEC-004', 'FREQUENCY_LIMIT_EXCEEDED', 'ELECTRICAL', 4, 'ERROR'],
  ['ALLOC-001', 'PIN_ALREADY_ALLOCATED', 'ALLOCATION', 5, 'ERROR'],
  ['ALLOC-002', 'PIN_MUX_CONFLICT', 'ALLOCATION', 5, 'ERROR'],
  ['ALLOC-003', 'RESOURCE_ALREADY_ALLOCATED', 'ALLOCATION', 5, 'ERROR'],
  ['ALLOC-004', 'CHANNEL_ALREADY_ALLOCATED', 'ALLOCATION', 5, 'ERROR'],
  ['ALLOC-005', 'PIN_MAPPING_INCOMPLETE', 'ALLOCATION', 5, 'ERROR'],
  ['ALLOC-006', 'RESOURCE_FULLY_ALLOCATED', 'ALLOCATION', 5, 'INFO'],
  ['BUS-001', 'BUS_ROLE_INVALID', 'BUS', 6, 'ERROR'],
  ['BUS-002', 'BUS_INTERFACE_MISMATCH', 'BUS', 6, 'ERROR'],
  ['BUS-003', 'I2C_ADDRESS_CONFLICT', 'BUS', 6, 'ERROR'],
  ['BUS-004', 'I2C_ADDRESS_UNRESOLVED', 'BUS', 6, 'WARNING'],
  ['BUS-005', 'SPI_CHIP_SELECT_CONFLICT', 'BUS', 6, 'ERROR'],
  ['BUS-006', 'MODBUS_ADDRESS_CONFLICT', 'BUS', 6, 'ERROR'],
  ['BUS-007', 'MODBUS_ADDRESS_INVALID', 'BUS', 6, 'ERROR'],
  ['POWER-001', 'POWER_ROLE_INVALID', 'POWER', 7, 'ERROR'],
  ['POWER-002', 'POWER_VOLTAGE_INCOMPATIBLE', 'POWER', 7, 'ERROR'],
  ['POWER-003', 'POWER_CURRENT_EXCEEDED', 'POWER', 7, 'ERROR'],
  ['POWER-004', 'POWER_MARGIN_LOW', 'POWER', 7, 'WARNING'],
  ['POWER-005', 'POWER_DATA_INCOMPLETE', 'POWER', 7, 'WARNING'],
  ['POWER-006', 'POWER_POLARITY_MISMATCH', 'POWER', 7, 'ERROR'],
  ['COMP-001', 'MISSING_REQUIRED_CONNECTION', 'COMPLETENESS', 7, 'ERROR'],
  ['COMP-002', 'UNVERIFIED_COMPONENT', 'COMPLETENESS', 7, 'WARNING'],
  ['COMP-003', 'DEPRECATED_COMPONENT', 'COMPLETENESS', 7, 'WARNING'],
  ['COMP-004', 'DISABLED_COMPONENT', 'COMPLETENESS', 7, 'WARNING'],
  ['COMP-005', 'COMPONENT_UPDATE_AVAILABLE', 'COMPLETENESS', 7, 'INFO'],
] as const;

export const RULE_REGISTRY: readonly RuleMetadata[] = Object.freeze(
  entries.map(([ruleId, code, category, phase, defaultSeverity]) =>
    Object.freeze({ ruleId, code, category, phase, defaultSeverity }),
  ),
);

export const RULES_BY_ID = new Map(RULE_REGISTRY.map((rule) => [rule.ruleId, rule]));
